services:
  frontend:
    build:
      context: ./apps/sgta-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./apps/sgta-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  python:
    build:
      context: ./apps/func-python
      dockerfile: Dockerfile
    container_name: sgta-function-app
    ports:
      - "8000:8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/topics/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    volumes:
      - ./cache:/app/cache  # Mount cache directory to persist FAISS embeddings
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
