import { Profesor } from "../types";

export const profesoresMock: Profesor[] = [
  {
    id: 1,
    nombres: "Manuel",
    primerApellido: "Vázquez",
    segundoApellido: "",
    correo: "mvazquez@pucp.edu.pe",
    codigo: "20150734",
    rolesAsignados: ["asesor", "jurado"],
    tesisActivas: 3,
    estado: "activo",
  },
  {
    id: 2,
    nombres: "Laura",
    primerApellido: "Martínez",
    segundoApellido: "",
    correo: "lmartinez@pucp.edu.pe",
    codigo: "19980452",
    rolesAsignados: ["asesor"],
    tesisActivas: 2,
    estado: "activo",
  },
  {
    id: 3,
    nombres: "Ana",
    primerApellido: "González",
    segundoApellido: "",
    correo: "agonzalez@pucp.edu.pe",
    codigo: "20050326",
    rolesAsignados: ["jurado"],
    tesisActivas: 0,
    estado: "activo",
  },
  {
    id: 4,
    nombres: "Carlos",
    primerApellido: "Pérez",
    segundoApellido: "",
    correo: "cperez@pucp.edu.pe",
    codigo: "20060444",
    rolesAsignados: ["asesor"],
    tesisActivas: 1,
    estado: "activo",
  },
  {
    id: 5,
    nombres: "Elena",
    primerApellido: "Torres",
    segundoApellido: "",
    correo: "etorres@pucp.edu.pe",
    codigo: "20070455",
    rolesAsignados: ["asesor", "jurado"],
    tesisActivas: 2,
    estado: "activo",
  },
  {
    id: 6,
    nombres: "Gabriel",
    primerApellido: "Díaz",
    segundoApellido: "",
    correo: "gdiaz@pucp.edu.pe",
    codigo: "20080466",
    rolesAsignados: ["jurado"],
    tesisActivas: 0,
    estado: "activo",
  },
  {
    id: 7,
    nombres: "Rosa",
    primerApellido: "Gutiérrez",
    segundoApellido: "",
    correo: "rgutierrez@pucp.edu.pe",
    codigo: "20090477",
    rolesAsignados: ["asesor"],
    tesisActivas: 4,
    estado: "activo",
  },
  {
    id: 8,
    nombres: "Luis",
    primerApellido: "Mendoza",
    segundoApellido: "",
    correo: "lmendoza@pucp.edu.pe",
    codigo: "20100488",
    rolesAsignados: ["asesor", "jurado"],
    tesisActivas: 1,
    estado: "activo",
  },
  {
    id: 9,
    nombres: "Valeria",
    primerApellido: "Ramírez",
    segundoApellido: "",
    correo: "vramirez@pucp.edu.pe",
    codigo: "20110499",
    rolesAsignados: ["asesor"],
    tesisActivas: 3,
    estado: "activo",
  },
  {
    id: 10,
    nombres: "Jorge",
    primerApellido: "Salazar",
    segundoApellido: "",
    correo: "jsalazar@pucp.edu.pe",
    codigo: "20120500",
    rolesAsignados: ["jurado"],
    tesisActivas: 0,
    estado: "activo",
  },
  {
    id: 11,
    nombres: "Patricia",
    primerApellido: "Silva",
    segundoApellido: "",
    correo: "psilva@pucp.edu.pe",
    codigo: "20130511",
    rolesAsignados: ["asesor"],
    tesisActivas: 2,
    estado: "activo",
  },
  {
    id: 12,
    nombres: "Mario",
    primerApellido: "López",
    segundoApellido: "",
    correo: "mlopez@pucp.edu.pe",
    codigo: "20140522",
    rolesAsignados: ["asesor", "jurado"],
    tesisActivas: 1,
    estado: "activo",
  },
  {
    id: 13,
    nombres: "Carmen",
    primerApellido: "Castro",
    segundoApellido: "",
    correo: "ccastro@pucp.edu.pe",
    codigo: "20150533",
    rolesAsignados: ["jurado"],
    tesisActivas: 0,
    estado: "activo",
  },
];