export const temasDataMock = [
  {
    id: 1,
    titulo: "Implementación de algoritmos de aprendizaje",
    area: "Inteligencia Artificial",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: [{ nombre: "Carlos Mendoza", codigo: "" }],
    postulaciones: null,
    estado: "aprobado",
    tipo: "inscrito",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 2,
    titulo: "Desarrollo de un sistema de monitoreo",
    area: "Internet de las Cosas",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: null,
    postulaciones: 3,
    estado: "disponible",
    tipo: "libre",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 3,
    titulo: "Análisis comparativo de frameworks de desarrollo web",
    area: "Desarrollo Web",
    asesor: "Dr. Miguel Torres",
    estudiantes: [
      { nombre: "Luis Rodríguez", codigo: "" },
      { nombre: "María Pérez", codigo: "" },
    ],
    postulaciones: null,
    estado: "aprobado",
    tipo: "interesado",
    ciclo: "2023-1",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 4,
    titulo: "Diseño e implementación de un sistema de datos",
    area: "Ciencia de Datos",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: [{ nombre: "María Torres", codigo: "" }],
    postulaciones: null,
    estado: "aprobado",
    tipo: "inscrito",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 5,
    titulo: "Optimización de consultas en bases de datos",
    area: "Bases de Datos",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: null,
    postulaciones: 5,
    estado: "disponible",
    tipo: "libre",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
];

