export enum EstadoTemaNombre {
  PROPUESTO_LIBRE = "PROPUESTO_LIBRE",
  PROPUESTO_GENERAL = "PROPUESTO_GENERAL",
  PROPUESTO_DIRECTO = "PROPUESTO_DIRECTO",
  PREINSCRITO = "PREINSCRITO",
  INSCRITO = "INSCRITO",
  REGISTRADO = "REGISTRADO",
  RECHAZADO = "RECHAZADO",
  EN_PROGRESO = "EN_PROGRESO",
  PAUSADO = "PAUSADO",
  FINALIZADO = "FINALIZADO",
  OBSERVADO = "OBSERVADO",
  VENCIDO = "VENCIDO",
}
