import { Coasesor, Tema, TemaForm } from "./entities";

export const emptyTemaForm: TemaForm = {
  tipoRegistro: "",
  titulo: "",
  areaInvestigacion: "",
  descripcion: "",
  coasesores: [],
  asesorPrincipal: "Dr. Roberto Sánchez",
  estudiantes: [],
  requisitos: "",
  fechaLimite: "",
};

export const temaVacio: Tema = {
  id: 0,
  codigo: null,
  titulo: "",
  resumen: "",
  objetivos: "",
  metodologia: "",
  portafolioUrl: "",
  activo: false,
  fechaLimite: "",
  fechaCreacion: "",
  fechaModificacion: null,
  estadoTemaNombre: null,
  carrera: null,
  idUsuarioInvolucradosList: null,
  idCoasesorInvolucradosList: null,
  idEstudianteInvolucradosList: null,
  idSubAreasConocimientoList: null,
  coasesores: [],
  tesistas: [],
  subareas: [],
  requisitos: "",
};

export const coasesoresData: Coasesor[] = [
  {
    id: 1,
    tipoUsuario: "coasesor",
    codigoPucp: "20230001",
    nombres: "Carmen",
    primerApellido: "Vega",
    segundoApellido: "",
    correoElectronico: "carmen.vega@pucp.edu.pe",
    nivelEstudios: "Doctorado",
    contrasena: null,
    biografia: null,
    enlaceRepositorio: null,
    enlaceLinkedin: null,
    disponibilidad: "Disponible",
    tipoDisponibilidad: "Tiempo parcial",
    activo: true,
    fechaCreacion: "2025-05-08T00:00:00Z",
    fechaModificacion: null,
  },
  {
    id: 2,
    tipoUsuario: "coasesor",
    codigoPucp: "20230002",
    nombres: "Miguel",
    primerApellido: "Torres",
    segundoApellido: "",
    correoElectronico: "miguel.torres@pucp.edu.pe",
    nivelEstudios: "Doctorado",
    contrasena: null,
    biografia: null,
    enlaceRepositorio: null,
    enlaceLinkedin: null,
    disponibilidad: "Disponible",
    tipoDisponibilidad: "Tiempo parcial",
    activo: true,
    fechaCreacion: "2025-05-08T00:00:00Z",
    fechaModificacion: null,
  },
  {
    id: 3,
    tipoUsuario: "coasesor",
    codigoPucp: "20230003",
    nombres: "Laura",
    primerApellido: "Mendoza",
    segundoApellido: "",
    correoElectronico: "laura.mendoza@pucp.edu.pe",
    nivelEstudios: "Doctorado",
    contrasena: null,
    biografia: null,
    enlaceRepositorio: null,
    enlaceLinkedin: null,
    disponibilidad: "Disponible",
    tipoDisponibilidad: "Tiempo parcial",
    activo: true,
    fechaCreacion: "2025-05-08T00:00:00Z",
    fechaModificacion: null,
  },
  {
    id: 4,
    tipoUsuario: "coasesor",
    codigoPucp: "20230004",
    nombres: "Javier",
    primerApellido: "Pérez",
    segundoApellido: "",
    correoElectronico: "javier.perez@pucp.edu.pe",
    nivelEstudios: "Doctorado",
    contrasena: null,
    biografia: null,
    enlaceRepositorio: null,
    enlaceLinkedin: null,
    disponibilidad: "Disponible",
    tipoDisponibilidad: "Tiempo parcial",
    activo: true,
    fechaCreacion: "2025-05-08T00:00:00Z",
    fechaModificacion: null,
  },
];

// export const estudiantesData: Tesista[] = [
//   {
//     id: 1,
//     tipoUsuario: "tesista",
//     codigoPucp: "20190123",
//     nombres: "Ana",
//     primerApellido: "García",
//     segundoApellido: "",
//     correoElectronico: "ana.garcia@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 2,
//     tipoUsuario: "tesista",
//     codigoPucp: "20190456",
//     nombres: "Pedro",
//     primerApellido: "López",
//     segundoApellido: "",
//     correoElectronico: "pedro.lopez@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 3,
//     tipoUsuario: "tesista",
//     codigoPucp: "20180789",
//     nombres: "Carlos",
//     primerApellido: "Mendoza",
//     segundoApellido: "",
//     correoElectronico: "carlos.mendoza@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 4,
//     tipoUsuario: "tesista",
//     codigoPucp: "20180111",
//     nombres: "María",
//     primerApellido: "Torres",
//     segundoApellido: "",
//     correoElectronico: "maria.torres@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 5,
//     tipoUsuario: "tesista",
//     codigoPucp: "20180222",
//     nombres: "Juan",
//     primerApellido: "Pérez",
//     segundoApellido: "",
//     correoElectronico: "juan.perez@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 6,
//     tipoUsuario: "tesista",
//     codigoPucp: "20190789",
//     nombres: "Roberto",
//     primerApellido: "Sánchez",
//     segundoApellido: "",
//     correoElectronico: "roberto.sanchez@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
//   {
//     id: 7,
//     tipoUsuario: "tesista",
//     codigoPucp: "20191000",
//     nombres: "Diego",
//     primerApellido: "Flores",
//     segundoApellido: "",
//     correoElectronico: "diego.flores@pucp.edu.pe",
//     nivelEstudios: "Pregrado",
//     contrasena: null,
//     biografia: null,
//     enlaceRepositorio: null,
//     enlaceLinkedin: null,
//     disponibilidad: "Disponible",
//     tipoDisponibilidad: "Tiempo completo",
//     activo: true,
//     fechaCreacion: "2025-05-08T00:00:00Z",
//     fechaModificacion: null,
//   },
// ];

// export const temasDataMock: Tema[] = [
//   {
//     id: 1,
//     codigo: null,
//     titulo: "Implementación de algoritmos de aprendizaje",
//     resumen: "Resumen del tema 1",
//     objetivos: "Objetivos del tema 1",
//     metodologia: "Metodología del tema 1",
//     portafolioUrl: "https://mi-portfolio.com/tema1",
//     activo: true,
//     fechaLimite: "2025-06-01T12:00:00Z",
//     fechaCreacion: "2025-05-01T12:00:00Z",
//     fechaModificacion: null,
//     estadoTemaNombre: "INSCRITO",
//     carrera: { id: 1 },
//     idUsuarioInvolucradosList: null,
//     idCoasesorInvolucradosList: null,
//     idEstudianteInvolucradosList: null,
//     idSubAreasConocimientoList: null,
//     coasesores: [
//       {
//         id: 1,
//         tipoUsuario: "Coasesor",
//         codigoPucp: "20201234",
//         nombres: "Carlos",
//         primerApellido: "Pérez",
//         segundoApellido: "Gonzales",
//         correoElectronico: "carlos.perez@pucp.edu.pe",
//         nivelEstudios: "Maestría",
//         contrasena: null, // Se asume que no se expone directamente
//         biografia:
//           "Especialista en inteligencia artificial con más de 10 años de experiencia en investigación y docencia.",
//         enlaceRepositorio: "https://github.com/carlosperez",
//         enlaceLinkedin: "https://linkedin.com/in/carlosperez",
//         disponibilidad: "Lunes a viernes de 9am a 12pm",
//         tipoDisponibilidad: "Parcial",
//         activo: true,
//         fechaCreacion: "2025-05-07T10:30:00Z",
//         fechaModificacion: null,
//       },
//     ],
//     tesistas: [
//       {
//         id: 1,
//         tipoUsuario: null,
//         codigoPucp: "20190123",
//         nombres: "Carlos Mendoza",
//         primerApellido: "",
//         segundoApellido: "",
//         correoElectronico: "",
//         nivelEstudios: null,
//         contrasena: null,
//         biografia: null,
//         enlaceRepositorio: null,
//         enlaceLinkedin: null,
//         disponibilidad: null,
//         tipoDisponibilidad: null,
//         activo: true,
//         fechaCreacion: "2025-05-01T12:00:00Z",
//         fechaModificacion: null,
//       },
//       {
//         id: 2,
//         tipoUsuario: null,
//         codigoPucp: "20201929",
//         nombres: "Jorge Perez",
//         primerApellido: "",
//         segundoApellido: "",
//         correoElectronico: "",
//         nivelEstudios: null,
//         contrasena: null,
//         biografia: null,
//         enlaceRepositorio: null,
//         enlaceLinkedin: null,
//         disponibilidad: null,
//         tipoDisponibilidad: null,
//         activo: true,
//         fechaCreacion: "2025-05-01T12:00:00Z",
//         fechaModificacion: null,
//       },
//     ],
//     subareas: [],
//   },
//   {
//     id: 2,
//     codigo: null,
//     titulo: "Desarrollo de un sistema de monitoreo",
//     resumen: "Resumen del tema 2",
//     objetivos: "Objetivos del tema 2",
//     metodologia: "Metodología del tema 2",
//     portafolioUrl: "https://mi-portfolio.com/tema2",
//     activo: true,
//     fechaLimite: "2025-06-01T12:00:00Z",
//     fechaCreacion: "2025-05-01T12:00:00Z",
//     fechaModificacion: null,
//     estadoTemaNombre: "PROPUESTO_LIBRE",
//     carrera: { id: 1 },
//     idUsuarioInvolucradosList: null,
//     idCoasesorInvolucradosList: null,
//     idEstudianteInvolucradosList: null,
//     idSubAreasConocimientoList: null,
//     coasesores: [],
//     tesistas: null,
//     subareas: [],
//   },
//   {
//     id: 3,
//     codigo: null,
//     titulo: "Análisis comparativo de frameworks de desarrollo web",
//     resumen: "Resumen del tema 3",
//     objetivos: "Objetivos del tema 3",
//     metodologia: "Metodología del tema 3",
//     portafolioUrl: "https://mi-portfolio.com/tema3",
//     activo: true,
//     fechaLimite: "2025-06-01T12:00:00Z",
//     fechaCreacion: "2025-05-01T12:00:00Z",
//     fechaModificacion: null,
//     estadoTemaNombre: "REGISTRADO",
//     carrera: { id: 1 },
//     idUsuarioInvolucradosList: null,
//     idCoasesorInvolucradosList: null,
//     idEstudianteInvolucradosList: null,
//     idSubAreasConocimientoList: null,
//     coasesores: [],
//     tesistas: [
//       {
//         id: 2,
//         tipoUsuario: null,
//         codigoPucp: null,
//         nombres: "Luis Rodríguez",
//         primerApellido: "",
//         segundoApellido: "",
//         correoElectronico: "",
//         nivelEstudios: null,
//         contrasena: null,
//         biografia: null,
//         enlaceRepositorio: null,
//         enlaceLinkedin: null,
//         disponibilidad: null,
//         tipoDisponibilidad: null,
//         activo: true,
//         fechaCreacion: "2025-05-01T12:00:00Z",
//         fechaModificacion: null,
//       },
//       {
//         id: 3,
//         tipoUsuario: null,
//         codigoPucp: null,
//         nombres: "María Pérez",
//         primerApellido: "",
//         segundoApellido: "",
//         correoElectronico: "",
//         nivelEstudios: null,
//         contrasena: null,
//         biografia: null,
//         enlaceRepositorio: null,
//         enlaceLinkedin: null,
//         disponibilidad: null,
//         tipoDisponibilidad: null,
//         activo: true,
//         fechaCreacion: "2025-05-01T12:00:00Z",
//         fechaModificacion: null,
//       },
//     ],
//     subareas: [],
//   },
//   {
//     id: 4,
//     codigo: null,
//     titulo: "Diseño e implementación de un sistema de datos",
//     resumen: "Resumen del tema 4",
//     objetivos: "Objetivos del tema 4",
//     metodologia: "Metodología del tema 4",
//     portafolioUrl: "https://mi-portfolio.com/tema4",
//     activo: true,
//     fechaLimite: "2025-06-01T12:00:00Z",
//     fechaCreacion: "2025-05-01T12:00:00Z",
//     fechaModificacion: null,
//     estadoTemaNombre: "INSCRITO",
//     carrera: { id: 1 },
//     idUsuarioInvolucradosList: null,
//     idCoasesorInvolucradosList: null,
//     idEstudianteInvolucradosList: null,
//     idSubAreasConocimientoList: null,
//     coasesores: [],
//     tesistas: [
//       {
//         id: 4,
//         tipoUsuario: null,
//         codigoPucp: null,
//         nombres: "María Torres",
//         primerApellido: "",
//         segundoApellido: "",
//         correoElectronico: "",
//         nivelEstudios: null,
//         contrasena: null,
//         biografia: null,
//         enlaceRepositorio: null,
//         enlaceLinkedin: null,
//         disponibilidad: null,
//         tipoDisponibilidad: null,
//         activo: true,
//         fechaCreacion: "2025-05-01T12:00:00Z",
//         fechaModificacion: null,
//       },
//     ],
//     subareas: [],
//   },
//   {
//     id: 5,
//     codigo: null,
//     titulo: "Optimización de consultas en bases de datos",
//     resumen: "Resumen del tema 5",
//     objetivos: "Objetivos del tema 5",
//     metodologia: "Metodología del tema 5",
//     portafolioUrl: "https://mi-portfolio.com/tema5",
//     activo: true,
//     fechaLimite: "2025-06-01T12:00:00Z",
//     fechaCreacion: "2025-05-01T12:00:00Z",
//     fechaModificacion: null,
//     estadoTemaNombre: "PROPUESTO_LIBRE",
//     carrera: { id: 1 },
//     idUsuarioInvolucradosList: null,
//     idCoasesorInvolucradosList: null,
//     idEstudianteInvolucradosList: null,
//     idSubAreasConocimientoList: null,
//     coasesores: [],
//     tesistas: null,
//     subareas: [],
//   },
// ];
