import { TemaForm } from "./entidades";

export const emptyTemaForm: TemaForm = {
  tipoRegistro: "",
  titulo: "",
  areaInvestigacion: "",
  descripcion: "",
  coasesores: [],
  asesorPrincipal: "Dr. Roberto Sánchez",
  estudiantes: [],
  requisitos: "",
  fechaLimite: "",
};

export const coasesoresDisponibles = [
  "Dra. Carmen Vega",
  "Dr. Miguel Torres",
  "Dra. Laura Mendoza",
  "Dr. Javier Pérez",
];

export const estudiantesDisponibles = [
  "Ana García (20190123)",
  "Pedro López (20190456)",
  "Carlos Mendoza (20180789)",
  "María Torres (20180111)",
  "Juan Pérez (20180222)",
  "Roberto Sánchez (20190789)",
  "Diego Flores (20191000)",
];

export const areasDeInvestigacion = [
  { key: "ia", name: "Inteligencia Artificial" },
  { key: "web", name: "Desarrollo Web" },
  { key: "datos", name: "Ciencia de Datos" },
  { key: "iot", name: "Internet de las Cosas" },
  { key: "seguridad", name: "Seguridad Informática" },
  { key: "bd", name: "Bases de Datos" },
  { key: "grafica", name: "Computación Gráfica" },
  { key: "redes", name: "Redes y Comunicaciones" },
  { key: "pln", name: "Procesamiento de Lenguaje Natural" },
  { key: "vr", name: "Realidad Virtual y Aumentada" },
];

export const temasDataMock = [
  {
    id: 1,
    titulo: "Implementación de algoritmos de aprendizaje",
    area: "Inteligencia Artificial",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: [{ nombre: "Carlos Mendoza", codigo: "" }],
    postulaciones: null,
    estado: "aprobado",
    tipo: "inscrito",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 2,
    titulo: "Desarrollo de un sistema de monitoreo",
    area: "Internet de las Cosas",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: null,
    postulaciones: 3,
    estado: "disponible",
    tipo: "libre",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 3,
    titulo: "Análisis comparativo de frameworks de desarrollo web",
    area: "Desarrollo Web",
    asesor: "Dr. Miguel Torres",
    estudiantes: [
      { nombre: "Luis Rodríguez", codigo: "" },
      { nombre: "María Pérez", codigo: "" },
    ],
    postulaciones: null,
    estado: "aprobado",
    tipo: "interesado",
    ciclo: "2023-1",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 4,
    titulo: "Diseño e implementación de un sistema de datos",
    area: "Ciencia de Datos",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: [{ nombre: "María Torres", codigo: "" }],
    postulaciones: null,
    estado: "aprobado",
    tipo: "inscrito",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
  {
    id: 5,
    titulo: "Optimización de consultas en bases de datos",
    area: "Bases de Datos",
    asesor: "Dr. Roberto Sánchez",
    estudiantes: null,
    postulaciones: 5,
    estado: "disponible",
    tipo: "libre",
    ciclo: "2023-2",
    descripcion: "",
    coasesores: [],
    recursos: [{ nombre: "", tipo: "", fecha: "" }],
  },
];

