import { TemaForm, TemaUI } from "./entidades";

// Se utilizan para diferenciar diferentes pestañas en la interfaz de Temas.
export enum TabValues {
  TODOS = "todos",
  INSCRITO = "inscrito",
  LIBRE = "libre",
  INTERESADO = "interesado",
}

// Estados
export enum estadosValues {
  PROPUESTO_LIBRE = "disponible",
  INSCRITO = "inscrito",
  REGISTRADO = "aprobado",
  RECHAZADO = "rechazado",
  EN_PROGRESO = "en progreso",
  PAUSADO = "pausado",
  FINALIZADO = "finalizado",
  OBSERVADO = "observado",
  VENCIDO = "vencido",
}

// tipo: Indica el origen del tema en relación con el asesor/coasesor
export const temaViewStates = [
  {
    id: 1,
    estadoNombre: "PROPUESTO_LIBRE",
    estado: "Disponible",
    tipo: TabValues.LIBRE,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 2,
    estadoNombre: "INSCRITO",
    estado: "Inscrito",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 3,
    estadoNombre: "REGISTRADO",
    estado: "Aprobado",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 4,
    estadoNombre: "RECHAZADO",
    estado: "Rechazado",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 5,
    estadoNombre: "EN_PROGRESO",
    estado: "En progreso",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 6,
    estadoNombre: "PAUSADO",
    estado: "Pausado",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 7,
    estadoNombre: "FINALIZADO",
    estado: "Finalizado",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 8,
    estadoNombre: "OBSERVADO",
    estado: "Observado",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 9,
    estadoNombre: "VENCIDO",
    estado: "Vencido",
    tipo: TabValues.INSCRITO,
    permisos: { edit: true, delete: true, viewDetails: true },
  },
  {
    id: 10,
    estadoNombre: "REGISTRADO",
    estado: "Aprobado",
    tipo: TabValues.INTERESADO,
    permisos: { edit: false, delete: false, viewDetails: true },
  },
];

export const emptyTemaForm: TemaForm = {
  tipoRegistro: "",
  titulo: "",
  areaInvestigacion: "",
  descripcion: "",
  coasesores: [],
  asesorPrincipal: "Dr. Roberto Sánchez",
  estudiantes: [],
  requisitos: "",
  fechaLimite: "",
};

export const coasesoresDisponibles = [
  "Dra. Carmen Vega",
  "Dr. Miguel Torres",
  "Dra. Laura Mendoza",
  "Dr. Javier Pérez",
];

export const estudiantesDisponibles = [
  "Ana García (20190123)",
  "Pedro López (20190456)",
  "Carlos Mendoza (20180789)",
  "María Torres (20180111)",
  "Juan Pérez (20180222)",
  "Roberto Sánchez (20190789)",
  "Diego Flores (20191000)",
];

export const areasDeInvestigacion = [
  { key: "ia", name: "Inteligencia Artificial" },
  { key: "web", name: "Desarrollo Web" },
  { key: "datos", name: "Ciencia de Datos" },
  { key: "iot", name: "Internet de las Cosas" },
  { key: "seguridad", name: "Seguridad Informática" },
  { key: "bd", name: "Bases de Datos" },
  { key: "grafica", name: "Computación Gráfica" },
  { key: "redes", name: "Redes y Comunicaciones" },
  { key: "pln", name: "Procesamiento de Lenguaje Natural" },
  { key: "vr", name: "Realidad Virtual y Aumentada" },
];

export const temasDataMock: TemaUI[] = [
  {
    id: 1,
    codigo: null,
    titulo: "Implementación de algoritmos de aprendizaje",
    resumen: "Resumen del tema 1",
    objetivos: "Objetivos del tema 1",
    metodologia: "Metodología del tema 1",
    portafolioUrl: "https://mi-portfolio.com/tema1",
    activo: true,
    fechaLimite: "2025-06-01T12:00:00Z",
    fechaCreacion: "2025-05-01T12:00:00Z",
    fechaModificacion: null,
    estadoTemaNombre: "aprobado",
    carrera: null,
    idUsuarioInvolucradosList: null,
    idCoasesorInvolucradosList: null,
    idEstudianteInvolucradosList: null,
    idSubAreasConocimientoList: null,
    coasesores: [],
    tesistas: [
      {
        id: 1,
        tipoUsuario: null,
        codigoPucp: null,
        nombres: "Carlos Mendoza",
        primerApellido: "",
        segundoApellido: "",
        correoElectronico: "",
        nivelEstudios: null,
        contrasena: null,
        biografia: null,
        enlaceRepositorio: null,
        enlaceLinkedin: null,
        disponibilidad: null,
        tipoDisponibilidad: null,
        activo: true,
        fechaCreacion: "2025-05-01T12:00:00Z",
        fechaModificacion: null,
      },
    ],
    subareas: [],
    tipo: "inscrito",
  },
  {
    id: 2,
    codigo: null,
    titulo: "Desarrollo de un sistema de monitoreo",
    resumen: "Resumen del tema 2",
    objetivos: "Objetivos del tema 2",
    metodologia: "Metodología del tema 2",
    portafolioUrl: "https://mi-portfolio.com/tema2",
    activo: true,
    fechaLimite: "2025-06-01T12:00:00Z",
    fechaCreacion: "2025-05-01T12:00:00Z",
    fechaModificacion: null,
    estadoTemaNombre: "disponible",
    carrera: null,
    idUsuarioInvolucradosList: null,
    idCoasesorInvolucradosList: null,
    idEstudianteInvolucradosList: null,
    idSubAreasConocimientoList: null,
    coasesores: [],
    tesistas: null,
    subareas: [],
    tipo: "libre",
  },
  {
    id: 3,
    codigo: null,
    titulo: "Análisis comparativo de frameworks de desarrollo web",
    resumen: "Resumen del tema 3",
    objetivos: "Objetivos del tema 3",
    metodologia: "Metodología del tema 3",
    portafolioUrl: "https://mi-portfolio.com/tema3",
    activo: true,
    fechaLimite: "2025-06-01T12:00:00Z",
    fechaCreacion: "2025-05-01T12:00:00Z",
    fechaModificacion: null,
    estadoTemaNombre: "aprobado",
    carrera: null,
    idUsuarioInvolucradosList: null,
    idCoasesorInvolucradosList: null,
    idEstudianteInvolucradosList: null,
    idSubAreasConocimientoList: null,
    coasesores: [],
    tesistas: [
      {
        id: 2,
        tipoUsuario: null,
        codigoPucp: null,
        nombres: "Luis Rodríguez",
        primerApellido: "",
        segundoApellido: "",
        correoElectronico: "",
        nivelEstudios: null,
        contrasena: null,
        biografia: null,
        enlaceRepositorio: null,
        enlaceLinkedin: null,
        disponibilidad: null,
        tipoDisponibilidad: null,
        activo: true,
        fechaCreacion: "2025-05-01T12:00:00Z",
        fechaModificacion: null,
      },
      {
        id: 3,
        tipoUsuario: null,
        codigoPucp: null,
        nombres: "María Pérez",
        primerApellido: "",
        segundoApellido: "",
        correoElectronico: "",
        nivelEstudios: null,
        contrasena: null,
        biografia: null,
        enlaceRepositorio: null,
        enlaceLinkedin: null,
        disponibilidad: null,
        tipoDisponibilidad: null,
        activo: true,
        fechaCreacion: "2025-05-01T12:00:00Z",
        fechaModificacion: null,
      },
    ],
    subareas: [],
    tipo: "interesado",
  },
  {
    id: 4,
    codigo: null,
    titulo: "Diseño e implementación de un sistema de datos",
    resumen: "Resumen del tema 4",
    objetivos: "Objetivos del tema 4",
    metodologia: "Metodología del tema 4",
    portafolioUrl: "https://mi-portfolio.com/tema4",
    activo: true,
    fechaLimite: "2025-06-01T12:00:00Z",
    fechaCreacion: "2025-05-01T12:00:00Z",
    fechaModificacion: null,
    estadoTemaNombre: "aprobado",
    carrera: null,
    idUsuarioInvolucradosList: null,
    idCoasesorInvolucradosList: null,
    idEstudianteInvolucradosList: null,
    idSubAreasConocimientoList: null,
    coasesores: [],
    tesistas: [
      {
        id: 4,
        tipoUsuario: null,
        codigoPucp: null,
        nombres: "María Torres",
        primerApellido: "",
        segundoApellido: "",
        correoElectronico: "",
        nivelEstudios: null,
        contrasena: null,
        biografia: null,
        enlaceRepositorio: null,
        enlaceLinkedin: null,
        disponibilidad: null,
        tipoDisponibilidad: null,
        activo: true,
        fechaCreacion: "2025-05-01T12:00:00Z",
        fechaModificacion: null,
      },
    ],
    subareas: [],
    tipo: "inscrito",
  },
  {
    id: 5,
    codigo: null,
    titulo: "Optimización de consultas en bases de datos",
    resumen: "Resumen del tema 5",
    objetivos: "Objetivos del tema 5",
    metodologia: "Metodología del tema 5",
    portafolioUrl: "https://mi-portfolio.com/tema5",
    activo: true,
    fechaLimite: "2025-06-01T12:00:00Z",
    fechaCreacion: "2025-05-01T12:00:00Z",
    fechaModificacion: null,
    estadoTemaNombre: "disponible",
    carrera: null,
    idUsuarioInvolucradosList: null,
    idCoasesorInvolucradosList: null,
    idEstudianteInvolucradosList: null,
    idSubAreasConocimientoList: null,
    coasesores: [],
    tesistas: null,
    subareas: [],
    tipo: "libre",
  },
];

export const asesorData = {
  id: 1,
  name: "Willians Gomez",
};

